Extended to support tar.gz and zip

diff --git a/extractfile b/extractfile
--- a/extractfile
+++ b/extractfile
@@ -1,47 +1,77 @@
 #!/bin/bash
 
-set -e
+set -e -x
 
+getFileFromTGZ() {
+
+	P=$1
+	TGZTMP=/tmp/tgz$$
+	mkdir -p $TGZTMP
+	cp $P $TGZTMP
+	cd $TGZTMP
+	FILE_LOCATION=`tar -tzf $P | grep "\/$FILE\$"`
+	tar xzf $P $FILE_LOCATION
+
+	cd $CURDIR
+	cp $TGZTMP/$FILE_LOCATION ./
+	
+	rm -Rf $TGZTMP
+}
 getFileFromDeb() {
 
-DEBTMP=/tmp/deb$$
-mkdir -p $DEBTMP
-cp $PACKAGE $DEBTMP
-cd $DEBTMP
-ar -vx $PACKAGE_FILENAME >/dev/null 2>/dev/null
-FILE_LOCATION=`tar -tzf data.tar.gz | grep "\/$FILE\$"`
+	DEBTMP=/tmp/deb$$
+	mkdir -p $DEBTMP
+	cp $PACKAGE $DEBTMP
+	cd $DEBTMP
+	ar -vx $PACKAGE_FILENAME >/dev/null 2>/dev/null
 
-tar xzf data.tar.gz $FILE_LOCATION
+	getFileFromTGZ $DEBTMP/data.tar.gz
 
-cd $CURDIR
-cp $DEBTMP/$FILE_LOCATION ./
-
-#cleanup
-rm -Rf $DEBTMP
-
+	#cleanup
+	rm -Rf $DEBTMP
 
 }
 
 getFileFromRpm() {
 
-RPMTMP=/tmp/rpm$$
-mkdir -p $RPMTMP
-cd $RPMTMP
+	RPMTMP=/tmp/rpm$$
+	mkdir -p $RPMTMP
+	cd $RPMTMP
 
-FILE_LOCATION=`rpm -qlp $PACKAGE| grep "\/$FILE\$"`
-rpm2cpio $PACKAGE| cpio -ivd .$FILE_LOCATION >/dev/null 2>&1
+	FILE_LOCATION=`rpm -qlp $PACKAGE| grep "\/$FILE\$"`
+	rpm2cpio $PACKAGE| cpio -ivd .$FILE_LOCATION >/dev/null 2>&1
 
-cd $CURDIR
+	cd $CURDIR
 
-cp $RPMTMP/$FILE_LOCATION ./
-rm -Rf $RPMTMP
+	cp $RPMTMP/$FILE_LOCATION ./
+	rm -Rf $RPMTMP
 
+}
+
+getFileFromZip() {
+
+	ZIPTMP=/tmp/zip$$
+	mkdir $ZIPTMP
+
+	cd $ZIPTMP
+	FILE_LOCATION=`unzip -l $PACKAGE | awk '{print $4}' | grep "\/$FILE\$"`
+
+	unzip -p $PACKAGE $FILE_LOCATION > $FILE
+
+	cd $CURDIR
+	cp $ZIPTMP/$FILE ./
+
+	rm -Rf $ZIPTMP
 }
 
 PACKAGE=$1
 FILE=$2
 PACKAGE_FILENAME=`echo $PACKAGE | sed 's/.*\///'`
-EXT=`echo $PACKAGE | sed 's/.*\.//'`
+EXT=${PACKAGE: -3}
+
+if [ "$EXT" = ".gz" ]; then
+	EXT=${PACKAGE: -6}
+fi
 
 CURDIR=`pwd`
 
@@ -51,6 +81,12 @@ case $EXT in
 		;;
 	rpm)
 		getFileFromRpm
+		;;
+	tar.gz)
+		getFileFromTGZ $PACKAGE
+		;;
+	zip)
+		getFileFromZip
 		;;
 	*)
 		>&2 echo "Unknown package type"
